-- Oracle Lookup Management System - Database Schema
-- Database: Oracle 21c Express Edition
-- Purpose: Create FND_LOOKUP_TYPES and FND_LOOKUP_VALUES tables

-- Drop existing tables if they exist (for development/re-initialization)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FND_LOOKUP_VALUES';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FND_LOOKUP_TYPES';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/

-- Create FND_LOOKUP_TYPES Table
CREATE TABLE FND_LOOKUP_TYPES (
    LOOKUP_TYPE         VARCHAR2(30)    NOT NULL PRIMARY KEY,
    MEANING             VARCHAR2(80)    NOT NULL,
    DESCRIPTION         VARCHAR2(240),
    CREATED_BY          VARCHAR2(50)    NOT NULL,
    CREATION_DATE       DATE            NOT NULL DEFAULT SYSDATE,
    LAST_UPDATED_BY     VARCHAR2(50)    NOT NULL,
    LAST_UPDATE_DATE    DATE            NOT NULL DEFAULT SYSDATE
);

CREATE INDEX IDX_LOOKUP_TYPES_MEANING ON FND_LOOKUP_TYPES(MEANING);

COMMENT ON TABLE FND_LOOKUP_TYPES IS 'Master lookup types for Oracle EBS lookup management';
COMMENT ON COLUMN FND_LOOKUP_TYPES.LOOKUP_TYPE IS 'Unique lookup type identifier (uppercase)';
COMMENT ON COLUMN FND_LOOKUP_TYPES.MEANING IS 'Display name for the lookup type';
COMMENT ON COLUMN FND_LOOKUP_TYPES.DESCRIPTION IS 'Additional documentation for the lookup type';
COMMENT ON COLUMN FND_LOOKUP_TYPES.CREATED_BY IS 'Audit: User ID who created the record';
COMMENT ON COLUMN FND_LOOKUP_TYPES.CREATION_DATE IS 'Audit: Timestamp of record creation';
COMMENT ON COLUMN FND_LOOKUP_TYPES.LAST_UPDATED_BY IS 'Audit: User ID who last updated the record';
COMMENT ON COLUMN FND_LOOKUP_TYPES.LAST_UPDATE_DATE IS 'Audit: Timestamp of last update';

-- Create FND_LOOKUP_VALUES Table
CREATE TABLE FND_LOOKUP_VALUES (
    LOOKUP_TYPE         VARCHAR2(30)    NOT NULL,
    LOOKUP_CODE         VARCHAR2(30)    NOT NULL,
    MEANING             VARCHAR2(80)    NOT NULL,
    DESCRIPTION         VARCHAR2(240),
    ENABLED_FLAG        VARCHAR2(1)     NOT NULL DEFAULT 'Y' CHECK (ENABLED_FLAG IN ('Y', 'N')),
    START_DATE_ACTIVE   DATE,
    END_DATE_ACTIVE     DATE,
    CREATED_BY          VARCHAR2(50)    NOT NULL,
    CREATION_DATE       DATE            NOT NULL DEFAULT SYSDATE,
    LAST_UPDATED_BY     VARCHAR2(50)    NOT NULL,
    LAST_UPDATE_DATE    DATE            NOT NULL DEFAULT SYSDATE,
    CONSTRAINT PK_LOOKUP_VALUES PRIMARY KEY (LOOKUP_TYPE, LOOKUP_CODE),
    CONSTRAINT FK_LOOKUP_VALUES_TYPE FOREIGN KEY (LOOKUP_TYPE) REFERENCES FND_LOOKUP_TYPES(LOOKUP_TYPE) ON DELETE CASCADE,
    CONSTRAINT CK_END_DATE_ACTIVE CHECK (END_DATE_ACTIVE IS NULL OR START_DATE_ACTIVE IS NULL OR END_DATE_ACTIVE >= START_DATE_ACTIVE)
);

CREATE INDEX IDX_LOOKUP_VALUES_TYPE ON FND_LOOKUP_VALUES(LOOKUP_TYPE);
CREATE INDEX IDX_LOOKUP_VALUES_CODE ON FND_LOOKUP_VALUES(LOOKUP_CODE);
CREATE INDEX IDX_LOOKUP_VALUES_MEANING ON FND_LOOKUP_VALUES(MEANING);
CREATE INDEX IDX_LOOKUP_VALUES_ENABLED ON FND_LOOKUP_VALUES(ENABLED_FLAG);

COMMENT ON TABLE FND_LOOKUP_VALUES IS 'Lookup values for Oracle EBS lookup management';
COMMENT ON COLUMN FND_LOOKUP_VALUES.LOOKUP_TYPE IS 'Reference to FND_LOOKUP_TYPES (FK, uppercase)';
COMMENT ON COLUMN FND_LOOKUP_VALUES.LOOKUP_CODE IS 'Unique code within lookup type (uppercase)';
COMMENT ON COLUMN FND_LOOKUP_VALUES.MEANING IS 'Display value for the lookup code';
COMMENT ON COLUMN FND_LOOKUP_VALUES.DESCRIPTION IS 'Additional documentation for the lookup code';
COMMENT ON COLUMN FND_LOOKUP_VALUES.ENABLED_FLAG IS 'Status flag: Y=Active, N=Inactive';
COMMENT ON COLUMN FND_LOOKUP_VALUES.START_DATE_ACTIVE IS 'Effective start date (inclusive)';
COMMENT ON COLUMN FND_LOOKUP_VALUES.END_DATE_ACTIVE IS 'Effective end date (inclusive)';
COMMENT ON COLUMN FND_LOOKUP_VALUES.CREATED_BY IS 'Audit: User ID who created the record';
COMMENT ON COLUMN FND_LOOKUP_VALUES.CREATION_DATE IS 'Audit: Timestamp of record creation';
COMMENT ON COLUMN FND_LOOKUP_VALUES.LAST_UPDATED_BY IS 'Audit: User ID who last updated the record';
COMMENT ON COLUMN FND_LOOKUP_VALUES.LAST_UPDATE_DATE IS 'Audit: Timestamp of last update';

-- Commit changes
COMMIT;

-- Verification queries
SELECT 'FND_LOOKUP_TYPES table created successfully' AS status FROM DUAL;
SELECT 'FND_LOOKUP_VALUES table created successfully' AS status FROM DUAL;
